config/routes.rb
Rails.application.routes.draw do
  get 'consults/index'

  resources :business_strategies

  resources :product_strategies

  resources :gtm_strategies

  resources :milestones

  resources :market_segmentations

  resources :acquisition_tracks

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'consults#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/business_strategy.rb
class BusinessStrategy < ActiveRecord::Base
  belongs_to :user
end

app/controllers/business_strategies_controller.rb
class BusinessStrategiesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_business_strategy, only: [:show, :edit, :update, :destroy]

  # GET /business_strategies
  # GET /business_strategies.json
  def index
    @business_strategies = BusinessStrategy.all
  end

  # GET /business_strategies/1
  # GET /business_strategies/1.json
  def show
  end

  # GET /business_strategies/new
  def new
    @business_strategy = BusinessStrategy.new
  end

  # GET /business_strategies/1/edit
  def edit
  end

  # POST /business_strategies
  # POST /business_strategies.json
  def create
    @business_strategy = BusinessStrategy.new(business_strategy_params)
    @business_strategy.user = current_user

    respond_to do |format|
      if @business_strategy.save
        format.html { redirect_to @business_strategy, notice: 'Business strategy was successfully created.' }
        format.json { render :show, status: :created, location: @business_strategy }
      else
        format.html { render :new }
        format.json { render json: @business_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /business_strategies/1
  # PATCH/PUT /business_strategies/1.json
  def update
    respond_to do |format|
      if @business_strategy.update(business_strategy_params)
        format.html { redirect_to @business_strategy, notice: 'Business strategy was successfully updated.' }
        format.json { render :show, status: :ok, location: @business_strategy }
      else
        format.html { render :edit }
        format.json { render json: @business_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /business_strategies/1
  # DELETE /business_strategies/1.json
  def destroy
    @business_strategy.destroy
    respond_to do |format|
      format.html { redirect_to business_strategies_url, notice: 'Business strategy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_business_strategy
      @business_strategy = BusinessStrategy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def business_strategy_params
      params.require(:business_strategy).permit(:vision, :principles, :business_model, :form_factor, :pricing, :sales, :user_id)
    end
end

app/helpers/business_strategies_helper.rb
module BusinessStrategiesHelper
end

app/views/business_strategies/_form.html.erb
<%= form_for @business_strategy, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :vision, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :vision, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :principles, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :principles, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :business_model, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :business_model, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :form_factor, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :form_factor, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :pricing, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :pricing, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :sales, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :sales, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  business_strategies_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/business_strategies/edit.html.erb
<%- model_class = BusinessStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => BusinessStrategy %></h1>
</div>
<%= render :partial => 'form' %>

app/views/business_strategies/index.html.erb
<%- model_class = BusinessStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => BusinessStrategy %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:vision) %></th>
      <th><%= model_class.human_attribute_name(:principles) %></th>
      <th><%= model_class.human_attribute_name(:business_model) %></th>
      <th><%= model_class.human_attribute_name(:form_factor) %></th>
      <th><%= model_class.human_attribute_name(:pricing) %></th>
      <th><%= model_class.human_attribute_name(:sales) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @business_strategies.each do |business_strategy| %>
      <tr>
        <td><%= business_strategy.id %></td>
        <td><%= business_strategy.vision %></td>
        <td><%= business_strategy.principles %></td>
        <td><%= business_strategy.business_model %></td>
        <td><%= business_strategy.form_factor %></td>
        <td><%= business_strategy.pricing %></td>
        <td><%= business_strategy.sales %></td>
        <td><%=l business_strategy.created_at, format: :long %></td>
        <td>
          <%= link_to business_strategy_path(business_strategy), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to business_strategy_path(business_strategy), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_business_strategy_path,
            :class => 'btn btn-primary' %>

app/views/business_strategies/new.html.erb
<%- model_class = BusinessStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => BusinessStrategy %></h1>
</div>
<%= render :partial => 'form' %>

app/views/business_strategies/show.html.erb
<%- model_class = BusinessStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => BusinessStrategy %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:vision) %></dt>
      <dd><pre class="prettyprint"><%= @business_strategy.vision %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:principles) %></dt>
      <dd><pre class="prettyprint"><%= @business_strategy.principles %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:business_model) %></dt>
      <dd><pre class="prettyprint"><%= @business_strategy.business_model %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:form_factor) %></dt>
      <dd><pre class="prettyprint"><%= @business_strategy.form_factor %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:pricing) %></dt>
      <dd><pre class="prettyprint"><%= @business_strategy.pricing %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:sales) %></dt>
      <dd><pre class="prettyprint"><%= @business_strategy.sales %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              business_strategies_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_business_strategy_path(@business_strategy), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              business_strategy_path(@business_strategy),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>