config/routes.rb
Rails.application.routes.draw do
  get 'consults/index'

  resources :business_strategies

  resources :product_strategies

  resources :gtm_strategies

  resources :milestones

  resources :market_segmentations

  resources :acquisition_tracks

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'consults#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/acquisition_track.rb
class AcquisitionTrack < ActiveRecord::Base
  belongs_to :market_segmentation
end

app/controllers/acquisition_tracks_controller.rb
class AcquisitionTracksController < ApplicationController
  before_action :set_acquisition_track, only: [:show, :edit, :update, :destroy]

  # GET /acquisition_tracks
  # GET /acquisition_tracks.json
  def index
    @acquisition_tracks = AcquisitionTrack.all
  end

  # GET /acquisition_tracks/1
  # GET /acquisition_tracks/1.json
  def show
  end

  # GET /acquisition_tracks/new
  def new
    @acquisition_track = AcquisitionTrack.new
  end

  # GET /acquisition_tracks/1/edit
  def edit
  end

  # POST /acquisition_tracks
  # POST /acquisition_tracks.json
  def create
    @acquisition_track = AcquisitionTrack.new(acquisition_track_params)

    respond_to do |format|
      if @acquisition_track.save
        format.html { redirect_to @acquisition_track, notice: 'Acquisition track was successfully created.' }
        format.json { render :show, status: :created, location: @acquisition_track }
      else
        format.html { render :new }
        format.json { render json: @acquisition_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /acquisition_tracks/1
  # PATCH/PUT /acquisition_tracks/1.json
  def update
    respond_to do |format|
      if @acquisition_track.update(acquisition_track_params)
        format.html { redirect_to @acquisition_track, notice: 'Acquisition track was successfully updated.' }
        format.json { render :show, status: :ok, location: @acquisition_track }
      else
        format.html { render :edit }
        format.json { render json: @acquisition_track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /acquisition_tracks/1
  # DELETE /acquisition_tracks/1.json
  def destroy
    @acquisition_track.destroy
    respond_to do |format|
      format.html { redirect_to acquisition_tracks_url, notice: 'Acquisition track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_acquisition_track
      @acquisition_track = AcquisitionTrack.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def acquisition_track_params
      params.require(:acquisition_track).permit(:user, :customer, :market_segmentation_id, :user_activity, :customer_activity, :plan_title, :date_scheduled)
    end
end

app/helpers/acquisition_tracks_helper.rb
module AcquisitionTracksHelper
end

app/views/acquisition_tracks/_form.html.erb
<%= form_for @acquisition_track, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :user, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :user, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :customer, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :customer, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :user_activity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :user_activity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :customer_activity, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :customer_activity, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :plan_title, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_field :plan_title, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :date_scheduled, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.datetime_select :date_scheduled, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  acquisition_tracks_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/acquisition_tracks/edit.html.erb
<%- model_class = AcquisitionTrack -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => AcquisitionTrack %></h1>
</div>
<%= render :partial => 'form' %>

app/views/acquisition_tracks/index.html.erb
<%- model_class = AcquisitionTrack -%>
<div class="page-header">
  <h1><%=t '.title', :default => AcquisitionTrack %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:user) %></th>
      <th><%= model_class.human_attribute_name(:customer) %></th>
      <th><%= model_class.human_attribute_name(:user_activity) %></th>
      <th><%= model_class.human_attribute_name(:customer_activity) %></th>
      <th><%= model_class.human_attribute_name(:plan_title) %></th>
      <th><%= model_class.human_attribute_name(:date_scheduled) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @acquisition_tracks.each do |acquisition_track| %>
      <tr>
        <td><%= acquisition_track.id %></td>
        <td><%= acquisition_track.user %></td>
        <td><%= acquisition_track.customer %></td>
        <td><%= acquisition_track.user_activity %></td>
        <td><%= acquisition_track.customer_activity %></td>
        <td><%= acquisition_track.plan_title %></td>
        <td><%= acquisition_track.date_scheduled %></td>
        <td><%=l acquisition_track.created_at, format: :long %></td>
        <td>
          <%= link_to acquisition_track_path(acquisition_track), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to acquisition_track_path(acquisition_track), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_acquisition_track_path,
            :class => 'btn btn-primary' %>

app/views/acquisition_tracks/new.html.erb
<%- model_class = AcquisitionTrack -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => AcquisitionTrack %></h1>
</div>
<%= render :partial => 'form' %>

app/views/acquisition_tracks/show.html.erb
<%- model_class = AcquisitionTrack -%>
<div class="page-header">
  <h1><%=t '.title', :default => AcquisitionTrack %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:user) %></dt>
      <dd><pre class="prettyprint"><%= @acquisition_track.user %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:customer) %></dt>
      <dd><pre class="prettyprint"><%= @acquisition_track.customer %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:user_activity) %></dt>
      <dd><pre class="prettyprint"><%= @acquisition_track.user_activity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:customer_activity) %></dt>
      <dd><pre class="prettyprint"><%= @acquisition_track.customer_activity %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:plan_title) %></dt>
      <dd><pre class="prettyprint"><%= @acquisition_track.plan_title %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:date_scheduled) %></dt>
      <dd><pre class="prettyprint"><%= @acquisition_track.date_scheduled %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              acquisition_tracks_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_acquisition_track_path(@acquisition_track), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              acquisition_track_path(@acquisition_track),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>