config/routes.rb
Rails.application.routes.draw do
  get 'consults/index'

  resources :business_strategies

  resources :product_strategies

  resources :gtm_strategies

  resources :milestones

  resources :market_segmentations

  resources :acquisition_tracks

  devise_for :users, controllers: {registrations: "users/registrations", sessions: "users/sessions", passwords: "users/passwords"}, skip: [:sessions, :registrations]
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  root 'consults#index'

  
  devise_scope :user do
    get    "login"   => "users/sessions#new",         as: :new_user_session
    post   "login"   => "users/sessions#create",      as: :user_session
    delete "signout" => "users/sessions#destroy",     as: :destroy_user_session
    
    get    "signup"  => "users/registrations#new",    as: :new_user_registration
    post   "signup"  => "users/registrations#create", as: :user_registration
    put    "signup"  => "users/registrations#update", as: :update_user_registration
    get    "account" => "users/registrations#edit",   as: :edit_user_registration
  end

end

app/models/product_strategy.rb
class ProductStrategy < ActiveRecord::Base
  belongs_to :user
end

app/controllers/product_strategies_controller.rb
class ProductStrategiesController < ApplicationController

  #->Prelang (scaffolding:rails/scope_to_user)
  before_filter :require_user_signed_in, only: [:new, :edit, :create, :update, :destroy]

  before_action :set_product_strategy, only: [:show, :edit, :update, :destroy]

  # GET /product_strategies
  # GET /product_strategies.json
  def index
    @product_strategies = ProductStrategy.all
  end

  # GET /product_strategies/1
  # GET /product_strategies/1.json
  def show
  end

  # GET /product_strategies/new
  def new
    @product_strategy = ProductStrategy.new
  end

  # GET /product_strategies/1/edit
  def edit
  end

  # POST /product_strategies
  # POST /product_strategies.json
  def create
    @product_strategy = ProductStrategy.new(product_strategy_params)
    @product_strategy.user = current_user

    respond_to do |format|
      if @product_strategy.save
        format.html { redirect_to @product_strategy, notice: 'Product strategy was successfully created.' }
        format.json { render :show, status: :created, location: @product_strategy }
      else
        format.html { render :new }
        format.json { render json: @product_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_strategies/1
  # PATCH/PUT /product_strategies/1.json
  def update
    respond_to do |format|
      if @product_strategy.update(product_strategy_params)
        format.html { redirect_to @product_strategy, notice: 'Product strategy was successfully updated.' }
        format.json { render :show, status: :ok, location: @product_strategy }
      else
        format.html { render :edit }
        format.json { render json: @product_strategy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /product_strategies/1
  # DELETE /product_strategies/1.json
  def destroy
    @product_strategy.destroy
    respond_to do |format|
      format.html { redirect_to product_strategies_url, notice: 'Product strategy was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_strategy
      @product_strategy = ProductStrategy.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_strategy_params
      params.require(:product_strategy).permit(:feature_list, :product_principles, :user_id)
    end
end

app/helpers/product_strategies_helper.rb
module ProductStrategiesHelper
end

app/views/product_strategies/_form.html.erb
<%= form_for @product_strategy, :html => { :class => 'form-horizontal form-model' } do |f| %>
  <div class="form-group">
    <%= f.label :feature_list, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :feature_list, :class => 'text-field form-control' %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :product_principles, :class => 'control-label col-md-2' %>
    <div class="col-md-10">
      <%= f.text_area :product_principles, :class => 'text-field form-control' %>
    </div>
  </div>

  <div class="form-group">
    <div class='col-md-offset-2 col-md-10'>
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                  product_strategies_path, :class => 'btn btn-default' %>
    </div>
  </div>
<% end %>

app/views/product_strategies/edit.html.erb
<%- model_class = ProductStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => ProductStrategy %></h1>
</div>
<%= render :partial => 'form' %>

app/views/product_strategies/index.html.erb
<%- model_class = ProductStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => ProductStrategy %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th>ID</th>
      <th><%= model_class.human_attribute_name(:feature_list) %></th>
      <th><%= model_class.human_attribute_name(:product_principles) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @product_strategies.each do |product_strategy| %>
      <tr>
        <td><%= product_strategy.id %></td>
        <td><%= product_strategy.feature_list %></td>
        <td><%= product_strategy.product_principles %></td>
        <td><%=l product_strategy.created_at, format: :long %></td>
        <td>
          <%= link_to product_strategy_path(product_strategy), :class => 'btn btn-xs', :title => "#{ t('.show', :default => t('helpers.links.show')) }" do %>
            <%= glyph 'info-sign' %>
            <%= glyph 'pencil' %>
          <%- end -%>
          <%= link_to product_strategy_path(product_strategy), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-xs', :title => "#{ t('.destroy', :default => t('helpers.links.destroy')) }" do %>
            <%= glyph 'remove' %>
          <%- end -%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_product_strategy_path,
            :class => 'btn btn-primary' %>

app/views/product_strategies/new.html.erb
<%- model_class = ProductStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => ProductStrategy %></h1>
</div>
<%= render :partial => 'form' %>

app/views/product_strategies/show.html.erb
<%- model_class = ProductStrategy -%>
<div class="page-header">
  <h1><%=t '.title', :default => ProductStrategy %></h1>
</div>

<div class="fieldset">
  <dl>
      <dt class="label label-default"><%= model_class.human_attribute_name(:feature_list) %></dt>
      <dd><pre class="prettyprint"><%= @product_strategy.feature_list %></pre></dd>
      <dt class="label label-default"><%= model_class.human_attribute_name(:product_principles) %></dt>
      <dd><pre class="prettyprint"><%= @product_strategy.product_principles %></pre></dd>
  </dl>
</div>

<div class="form-group">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              product_strategies_path, :class => 'btn btn-default'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_product_strategy_path(@product_strategy), :class => 'btn btn-default' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              product_strategy_path(@product_strategy),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>